<a href="https://colab.research.google.com/github/MiguelFigueroa02/MCPI_Student_Repo/blob/main/courses/1-Semester/fundamentals%20of%20statistics/Projects%20/Notebooks/Basic_Genetic_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import make_scorer, matthews_corrcoef
from sklearn.datasets import make_classification

In [2]:
mcc_scorer = make_scorer(matthews_corrcoef)

In [3]:
def evaluacion_individual(mask, X, y):
  n_features = int(mask.sum())

  if n_features == 0 or n_features> 4:
    return -1.0

  X_subset = X[:, mask.astype(bool)]

  model = LogisticRegression(
      solver="lbfgs",
      max_iter=5000
  )

  cv = StratifiedKFold(
      n_splits=5,
      shuffle=True,
      random_state=42
  )

  scores = cross_val_score(
      model,
      X_subset,
      y,
      cv=cv,
      scoring=mcc_scorer
  )

  return scores.mean()

In [4]:
def random_individual(n_features=10, max_features=4):
  while True:
    mask = np.random.randint(
        0,2,size=n_features
    )

    if 1<=mask.sum()<=max_features:
      return mask

In [5]:
X, y = make_classification(
    n_samples=30,
    n_features=10,
    n_informative=4,
    n_redundant=1,
    n_classes=3,
    n_clusters_per_class=1,
    class_sep=1.4,
    random_state=42
)

In [6]:
feature_names = [
    "M1", "M2", "M3", "M4", "M5",
    "M6", "M7", "M8", "M9", "M10"
]

In [7]:
pd.DataFrame(data=X, columns=feature_names)

,M1,M2,M3,M4,M5,M6,M7,M8,M9,M10
0,1.361819,-0.498407,-1.545566,-0.617896,-1.639730,-0.324395,1.096796,2.113112,-2.583375,0.524609
1,1.851821,0.183856,-1.189108,-1.898610,-2.379375,0.577897,-1.548829,-0.343129,-2.608636,2.134641
2,-0.992763,-0.699378,0.114098,-0.428498,-0.367851,-0.418509,0.591316,-0.883079,-2.574548,-0.111419
3,2.830116,-0.127735,-2.521714,-2.274976,-3.143601,-1.560557,0.195346,-0.555945,-1.673921,2.000348
4,0.376054,1.032513,0.034135,-1.940207,-1.732366,-1.034402,0.926233,0.607839,-3.350033,0.204283
5,-2.226592,2.273345,-0.717736,-1.598312,-0.733708,0.146975,0.418119,-1.886528,-0.915593,0.539609
6,2.707088,-1.551434,-1.899340,-1.750087,-2.751818,-0.510493,-1.801888,0.467717,-2.600558,-0.732951
7,-0.060140,-0.765509,-1.272960,0.280098,-0.496092,0.422314,-0.374522,-1.291216,-1.493868,-1.307914
8,-1.497601,-2.216761,1.450308,-2.228592,-0.312343,1.389566,0.448649,-0.078732,0.537656,1.870424
9,1.668255,-2.254159,1.718716,1.796849,0.863319,-2.456593,0.790594,0.632852,-1.963554,-0.076532
10,0.167911,-1.716424,0.639011,-2.712973,-1.750605,-1.042961,1.281920,-0.028421,-2.326547,1.326472
11,-1.083031,-0.127605,-2.135489,-1.269201,-1.242268,0.341591,0.327223,0.506575,-0.451486,2.118886
12,3.556533,-1.155516,1.919077,-3.271505,-2.316611,1.570111,-1.543725,1.116893,-1.175949,-1.124952
13,1.612394,0.413354,-1.181923,-2.013464,-2.199270,-0.140899,-1.498296,-0.011443,-1.480422,0.872162
14,1.607282,0.972633,1.569968,0.094100,-0.125040,1.544475,3.187033,0.084164,-1.851600,0.344068
15,-1.441656,-2.879457,-1.635383,-1.320807,-1.220763,-0.803178,-0.985382,-1.093940,-1.750795,-0.004857
16,0.853992,0.764478,1.218777,-1.059515,-0.625525,-1.111164,0.180493,1.071042,-1.330202,-0.862615
17,2.393398,0.840005,-1.802293,-2.326662,-3.201426,1.781291,-1.990600,-0.857549,-4.047478,-0.677416
18,2.726439,0.382799,1.355130,-1.344944,-1.458290,0.492141,1.688017,-0.615245,-2.803008,-1.527453
19,1.372723,-0.280655,-0.428652,-2.757112,-2.022166,-0.603976,-0.680004,-0.263406,0.289894,-0.549253
20,-2.569862,0.396774,-2.091798,-0.969434,-0.793284,-1.783251,-1.570812,1.479849,-1.174293,-0.243134
21,-0.393097,1.137017,0.676595,-0.723503,-0.324692,0.446890,0.481218,0.467057,-1.492724,-1.144949
22,-3.587135,0.850121,-1.061712,-0.972343,-0.166246,0.394340,1.300345,-1.343524,-1.045971,-0.004696
23,-1.262758,-1.112497,-1.730032,-1.453210,-1.311771,0.867229,-0.383323,-0.462527,-1.365113,0.958414
24,1.217885,-0.462925,-1.875132,-0.361396,-1.594391,0.086566,0.226849,1.655462,-2.747103,-0.592883
25,-1.487541,-1.147720,0.689749,-2.224320,-0.388052,1.389603,-1.341403,-1.621695,1.662214,-0.855241
26,-0.233167,-0.449304,-0.030495,-2.310593,-1.492354,0.418639,-1.027062,0.882838,-1.381850,-0.728179
27,-0.621101,-0.596897,-0.329828,-2.182061,-1.364273,-0.111204,1.546537,-0.949519,-1.029834,-1.749069
28,0.623155,0.149834,-0.096475,-1.981944,-1.440399,0.140907,-1.200132,1.201380,-0.728491,0.354420
29,0.548775,-0.510944,-0.510895,-1.982356,-1.726692,1.210399,-1.880313,0.966392,-1.750922,-0.151236

In [8]:
Individual = random_individual()
print(Individual)
selected = [feature_names[i] for i, value in enumerate(Individual) if value ==1]
print(selected)

[1 0 0 0 0 1 0 1 1 0]
['M1', 'M6', 'M8', 'M9']

In [9]:
score = evaluacion_individual(Individual, X, y)
print(score)

0.3745770242898356

In [10]:
poblacion = [random_individual() for _ in range(30)]

In [11]:
poblacion

[array([0, 1, 0, 0, 1, 0, 1, 0, 0, 1]),
 array([1, 0, 1, 0, 0, 0, 0, 0, 1, 1]),
 array([1, 1, 0, 1, 0, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0]),
 array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1]),
 array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0]),
 array([0, 0, 0, 1, 0, 1, 0, 0, 1, 1]),
 array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 0, 0, 1, 0, 1]),
 array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0]),
 array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1]),
 array([1, 0, 1, 0, 0, 1, 0, 0, 1, 0]),
 array([1, 1, 0, 0, 0, 0, 1, 0, 1, 0]),
 array([0, 0, 1, 1, 0, 0, 1, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 1, 1, 0, 0, 1]),
 array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0]),
 array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0]),
 array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0]),
 array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1]),
 array([0, 0, 1, 0, 1, 0, 0, 0, 1, 1]),
 array([1, 0, 0, 1, 0, 0, 0, 1, 0, 1]),
 array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1]),
 array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1])]

In [12]:
evaluaciones = [evaluacion_individual(ind, X, y) for ind in poblacion]
evaluaciones

[np.float64(0.317100954340678),
 np.float64(0.7442798883961064),
 np.float64(0.27363264736703374),
 np.float64(0.43581426785941507),
 np.float64(0.38760999803597834),
 np.float64(0.30889318714683733),
 np.float64(0.4343215646904345),
 np.float64(0.3835909710727057),
 np.float64(0.26111648393354675),
 np.float64(0.24515301754878283),
 np.float64(0.05222329678670935),
 np.float64(0.2901678377637934),
 np.float64(0.6266795614405123),
 np.float64(0.31885151085250935),
 np.float64(0.2901678377637934),
 np.float64(-0.16346054035628882),
 np.float64(0.06875848718346902),
 np.float64(0.7876099980359783),
 np.float64(0.2866656211131765),
 np.float64(0.47107480763921866),
 np.float64(0.4990610249106308),
 np.float64(0.3179071339297075),
 np.float64(0.7223537275031262),
 np.float64(0.5495996111222016),
 np.float64(0.33687940441824954),
 np.float64(0.7079542120574682),
 np.float64(0.3765865377714719),
 np.float64(0.5946144313372121),
 np.float64(0.3044465935734187),
 np.float64(0.7223537275031262)]

In [13]:
concate = pd.DataFrame({'máscara': poblacion, 'evaluación': evaluaciones})
concate.sort_values('evaluación', ascending=False)

                           máscara  evaluación
17  [1, 0, 1, 0, 0, 1, 0, 0, 1, 0]    0.787610
1   [1, 0, 1, 0, 0, 0, 0, 0, 1, 1]    0.744280
22  [1, 0, 1, 1, 1, 0, 0, 0, 0, 0]    0.722354
29  [1, 0, 1, 0, 1, 0, 0, 0, 0, 1]    0.722354
25  [0, 0, 1, 0, 1, 0, 0, 0, 1, 1]    0.707954
12  [1, 0, 0, 0, 1, 0, 0, 1, 0, 1]    0.626680
27  [0, 0, 1, 1, 0, 0, 0, 0, 1, 0]    0.594614
23  [0, 1, 1, 0, 1, 0, 0, 0, 1, 0]    0.549600
20  [1, 0, 0, 0, 0, 1, 1, 0, 0, 1]    0.499061
19  [0, 0, 1, 1, 0, 0, 1, 1, 0, 0]    0.471075
3   [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]    0.435814
6   [1, 1, 0, 0, 0, 0, 1, 1, 0, 0]    0.434322
4   [0, 0, 0, 0, 1, 1, 0, 1, 0, 0]    0.387610
7   [1, 0, 0, 0, 0, 0, 0, 1, 0, 0]    0.383591
26  [1, 0, 0, 1, 0, 0, 0, 1, 0, 1]    0.376587
24  [0, 0, 1, 0, 0, 0, 1, 0, 0, 1]    0.336879
13  [0, 0, 0, 1, 0, 0, 1, 1, 0, 0]    0.318852
21  [1, 0, 0, 1, 0, 0, 0, 0, 1, 0]    0.317907
0   [0, 1, 0, 0, 1, 0, 1, 0, 0, 1]    0.317101
5   [0, 1, 1, 1, 0, 0, 0, 0, 0, 0]    0.308893
28  [0, 0, 1, 1, 0, 1, 0, 0, 0, 1]    0.304447
11  [0, 1, 1, 0, 0, 0, 1, 0, 0, 0]    0.290168
14  [0, 1, 1, 0, 0, 0, 1, 0, 0, 0]    0.290168
18  [1, 1, 0, 0, 0, 0, 1, 0, 1, 0]    0.286666
2   [1, 1, 0, 1, 0, 0, 0, 1, 0, 0]    0.273633
8   [1, 0, 0, 0, 0, 1, 0, 1, 0, 1]    0.261116
9   [0, 1, 0, 0, 1, 0, 1, 0, 1, 0]    0.245153
16  [1, 1, 0, 0, 0, 0, 0, 0, 1, 1]    0.068758
10  [0, 0, 0, 1, 0, 1, 0, 0, 1, 1]    0.052223
15  [0, 1, 0, 1, 0, 1, 0, 0, 0, 0]   -0.163461

In [14]:
for ind, value in zip(poblacion, evaluaciones):

  print(ind, value)

[0 1 0 0 1 0 1 0 0 1] 0.317100954340678
[1 0 1 0 0 0 0 0 1 1] 0.7442798883961064
[1 1 0 1 0 0 0 1 0 0] 0.27363264736703374
[1 0 0 0 0 0 0 0 0 0] 0.43581426785941507
[0 0 0 0 1 1 0 1 0 0] 0.38760999803597834
[0 1 1 1 0 0 0 0 0 0] 0.30889318714683733
[1 1 0 0 0 0 1 1 0 0] 0.4343215646904345
[1 0 0 0 0 0 0 1 0 0] 0.3835909710727057
[1 0 0 0 0 1 0 1 0 1] 0.26111648393354675
[0 1 0 0 1 0 1 0 1 0] 0.24515301754878283
[0 0 0 1 0 1 0 0 1 1] 0.05222329678670935
[0 1 1 0 0 0 1 0 0 0] 0.2901678377637934
[1 0 0 0 1 0 0 1 0 1] 0.6266795614405123
[0 0 0 1 0 0 1 1 0 0] 0.31885151085250935
[0 1 1 0 0 0 1 0 0 0] 0.2901678377637934
[0 1 0 1 0 1 0 0 0 0] -0.16346054035628882
[1 1 0 0 0 0 0 0 1 1] 0.06875848718346902
[1 0 1 0 0 1 0 0 1 0] 0.7876099980359783
[1 1 0 0 0 0 1 0 1 0] 0.2866656211131765
[0 0 1 1 0 0 1 1 0 0] 0.47107480763921866
[1 0 0 0 0 1 1 0 0 1] 0.4990610249106308
[1 0 0 1 0 0 0 0 1 0] 0.3179071339297075
[1 0 1 1 1 0 0 0 0 0] 0.7223537275031262
[0 1 1 0 1 0 0 0 1 0] 0.5495996111222016
[0 0 1 0 0 0 1 0 0 1] 0.33687940441824954
[0 0 1 0 1 0 0 0 1 1] 0.7079542120574682
[1 0 0 1 0 0 0 1 0 1] 0.3765865377714719
[0 0 1 1 0 0 0 0 1 0] 0.5946144313372121
[0 0 1 1 0 1 0 0 0 1] 0.3044465935734187
[1 0 1 0 1 0 0 0 0 1] 0.7223537275031262

In [15]:
def torneo(poblacion, evaluaciones, k=3):
  indices = np.random.choice(
      len(poblacion),
      size=k,
      replace=False
  )
  print(indices)
  winner = indices[np.argmax(
      [evaluaciones[i] for i in indices]
  )]
  print(evaluaciones[winner])


  return poblacion[winner].copy()

In [16]:
ganador = torneo(poblacion, evaluaciones)
ganador

[11 20  9]
0.4990610249106308

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 1])

In [22]:
def two_point_crossover(a,b):
  points = sorted(
      np.random.choice(
          np.arange(1, len(a)),
          size = 2,
          replace=False
    )
  )
  p1, p2 = points
  child1=a.copy()
  child2=b.copy()

  child1[p1:p2], child2[p1:p2] = (
      a[p1:p2],
      b[p1:p2]
  )

  return child1, child2

In [23]:
def bit_flip_mutation(individual, indpb=0.2):
  child = individual.copy()
  for i in range(len(child)):
    if np.random.rand() < indpb:
      child[i] = 1 - child[i]

    return child

In [24]:
np.random.seed(1)

population_size = 30
n_generations = 12

crossover_probability = 0.5
mutation_probability = 0.2

population = [
    random_individual()
    for _ in range(population_size)
]

history = []

for generation in range(n_generations + 1):

    # 1. Evaluar población
    fitnesses = np.array([
        evaluacion_individual(ind, X, y)
        for ind in population
    ])

    # 2. Identificar mejor individuo
    best_index = np.argmax(fitnesses)

    best_individual = (
        population[best_index]
    )

    best_fitness = (
        fitnesses[best_index]
    )

    mean_fitness = (
        fitnesses.mean()
    )

    history.append({
        "generation": generation,
        "best_MCC": best_fitness,
        "mean_MCC": mean_fitness
    })

    print(
        f"Generation {generation:02d} | "
        f"Best MCC = {best_fitness:.3f} | "
        f"Mean MCC = {mean_fitness:.3f}"
    )

    # No crear nueva población después
    # de la última generación
    if generation == n_generations:
        break

    # 3. Elitismo:
    # conservar el mejor
    new_population = [
        best_individual.copy()
    ]

    # 4. Generar descendientes
    while len(new_population) < population_size:

        parent1 = torneo(
            population,
            fitnesses
        )

        parent2 = torneo(
            population,
            fitnesses
        )

        child1 = parent1.copy()
        child2 = parent2.copy()

        # Crossover
        if np.random.rand() < crossover_probability:

            child1, child2 = (
                two_point_crossover(
                    parent1,
                    parent2
                )
            )

        # Mutation
        if np.random.rand() < mutation_probability:
            child1 = bit_flip_mutation(
                child1
            )

        if np.random.rand() < mutation_probability:
            child2 = bit_flip_mutation(
                child2
            )

        # Reparar si excede máximo
        if child1.sum() > 4:
            ones = np.where(child1 == 1)[0]

            while child1.sum() > 4:
                child1[
                    np.random.choice(ones)
                ] = 0
                ones = np.where(child1 == 1)[0]

        if child1.sum() == 0:
            child1[
                np.random.randint(10)
            ] = 1

        if child2.sum() > 4:
            ones = np.where(child2 == 1)[0]

            while child2.sum() > 4:
                child2[
                    np.random.choice(ones)
                ] = 0
                ones = np.where(child2 == 1)[0]

        if child2.sum() == 0:
            child2[
                np.random.randint(10)
            ] = 1

        new_population.append(child1)

        if len(new_population) < population_size:
            new_population.append(child2)

    population = new_population

Generation 00 | Best MCC = 0.722 | Mean MCC = 0.334
[ 2 28  4]
0.3566698903601281
[28 23 24]
0.4430227444311138
[ 9  0 21]
0.4133397807202561
[25 23 22]
0.4430227444311138
[14  3  6]
0.7223537275031262
[28 24  4]
0.3566698903601281
[11 18 16]
0.5946144313372121
[16  3  2]
0.7223537275031262
[ 9 12 28]
0.7223537275031262
[20 28 10]
0.4935492947783776
[23 11 12]
0.7223537275031262
[ 2 22 28]
0.3566698903601281
[11  7 29]
0.7223537275031262
[ 9 28 25]
0.3566698903601281
[20 10  6]
0.4935492947783776
[10 21  1]
0.4133397807202561
[16  8 29]
0.7223537275031262
[ 1 12 29]
0.7223537275031262
[20 21 28]
0.4935492947783776
[ 8 22 27]
0.5044465935734187
[18  3 22]
0.7223537275031262
[12  1 23]
0.7223537275031262
[18 16 24]
0.5946144313372121
[19 12  5]
0.7223537275031262
[28  7 21]
0.4133397807202561
[ 3 22 23]
0.7223537275031262
[ 0 28  9]
0.3566698903601281
[ 8 24  6]
0.08647361370701845
[10 29 21]
0.7223537275031262
[21 26  4]
0.4288098345581813
Generation 01 | Best MCC = 0.722 | Mean MCC = 0.558
[11 21  4]
0.7223537275031262
[11 22  9]
0.7223537275031262
[19 25 15]
0.4935492947783776
[ 1 10 19]
0.4935492947783776
[13 27 24]
0.7223537275031262
[ 8 19 16]
0.7223537275031262
[10  6 14]
0.4935492947783776
[27 24 18]
0.7223537275031262
[ 6 29 27]
0.7223537275031262
[24  6  5]
0.7223537275031262
[17 25  9]
0.7223537275031262
[ 9  2 24]
0.7223537275031262
[15 25 10]
0.4935492947783776
[ 0 27 15]
0.7223537275031262
[14  9  5]
0.7223537275031262
[24  3  9]
0.7223537275031262
[14  3 13]
0.7223537275031262
[19 12 23]
0.5946144313372121
[ 4 19 17]
0.7223537275031262
[10 24  3]
0.7223537275031262
[24 19  4]
0.7223537275031262
[27  4  8]
0.7223537275031262
[ 2 25 15]
0.4935492947783776
[21 24  2]
0.7223537275031262
[26 16 21]
0.7223537275031262
[12 11 28]
0.7223537275031262
[23 13 16]
0.7223537275031262
[27 15  0]
0.7223537275031262
[18 23 15]
0.7223537275031262
[18 16  4]
0.7223537275031262
Generation 02 | Best MCC = 0.722 | Mean MCC = 0.673
[14 26 20]
0.7223537275031262
[23 26  3]
0.7223537275031262
[13 10 11]
0.7223537275031262
[24 21  0]
0.7223537275031262
[25 13 27]
0.7223537275031262
[10  4 21]
0.7223537275031262
[20  6 29]
0.7223537275031262
[ 4 19 27]
0.7223537275031262
[28 10 23]
0.7223537275031262
[21  7 17]
0.7223537275031262
[10  8 16]
0.7223537275031262
[15  4 19]
0.7223537275031262
[12  1  9]
0.7223537275031262
[13  2 26]
0.7223537275031262
[5 1 4]
0.7223537275031262
[11  2  9]
0.7223537275031262
[14  8 12]
0.7223537275031262
[17 24 27]
0.7223537275031262
[11 23 13]
0.7223537275031262
[28 15 16]
0.7223537275031262
[ 7 22  8]
0.7223537275031262
[ 0 20  3]
0.7223537275031262
[ 4  6 11]
0.7223537275031262
[ 3 19 18]
0.7223537275031262
[25 12  2]
0.7223537275031262
[16 29 21]
0.7223537275031262
[ 4 16 29]
0.7223537275031262
[14 20  2]
0.7223537275031262
[ 7 24  1]
0.7223537275031262
[7 1 3]
0.5133397807202561
Generation 03 | Best MCC = 0.722 | Mean MCC = 0.695
[10  5 22]
0.7223537275031262
[12  8 10]
0.7223537275031262
[ 3 12 15]
0.7223537275031262
[ 6  1 14]
0.7223537275031262
[17 27  5]
0.7223537275031262
[ 5 24 12]
0.7223537275031262
[ 3 20 15]
0.7223537275031262
[19 11  9]
0.7223537275031262
[ 0 24  5]
0.7223537275031262
[18  9  7]
0.7223537275031262
[29  6  9]
0.7223537275031262
[ 7 24 14]
0.7223537275031262
[17 11 21]
0.7223537275031262
[13 17  3]
0.7223537275031262
[ 2 21  1]
0.7223537275031262
[17  6 20]
0.7223537275031262
[13 16 22]
0.7223537275031262
[24 14  6]
0.7223537275031262
[23 28 17]
0.7223537275031262
[22  3 10]
0.7223537275031262
[16 29  0]
0.7223537275031262
[ 0 19 15]
0.7223537275031262
[ 5  8 13]
0.7223537275031262
[ 2 29  4]
0.7223537275031262
[24  4 29]
0.7223537275031262
[20 17  9]
0.7223537275031262
[ 5 28 10]
0.7223537275031262
[28  1 10]
0.7223537275031262
[24  9 11]
0.7223537275031262
[ 0 14 25]
0.7223537275031262
Generation 04 | Best MCC = 0.722 | Mean MCC = 0.708
[28  5 18]
0.7223537275031262
[19 29  1]
0.7223537275031262
[14 17 13]
0.7223537275031262
[25  7  0]
0.7223537275031262
[ 7 11 17]
0.7223537275031262
[27  7 24]
0.7223537275031262
[27  5 22]
0.7223537275031262
[24 20  2]
0.7223537275031262
[3 7 5]
0.7223537275031262
[ 1 26 29]
0.7223537275031262
[14 21 25]
0.7223537275031262
[ 5 16 18]
0.7223537275031262
[13  7  8]
0.7223537275031262
[23 10 26]
0.7223537275031262
[26 21 27]
0.7223537275031262
[28 26  0]
0.7223537275031262
[ 1  8 29]
0.7223537275031262
[18 28  1]
0.7223537275031262
[ 3 27 21]
0.7223537275031262
[7 1 9]
0.7223537275031262
[ 3 26  9]
0.7223537275031262
[ 5 19 23]
0.7223537275031262
[ 5 26  6]
0.7223537275031262
[15 26  2]
0.7223537275031262
[12 25  6]
0.7223537275031262
[10 24 22]
0.7223537275031262
[18 26  1]
0.7223537275031262
[ 8 21 11]
0.7223537275031262
[28 29 17]
0.7223537275031262
[10  7  2]
0.7223537275031262
Generation 05 | Best MCC = 0.722 | Mean MCC = 0.708
[10  4 22]
0.7223537275031262
[14  2 10]
0.7223537275031262
[10 20  5]
0.7223537275031262
[27  9 25]
0.7223537275031262
[22  2 18]
0.7223537275031262
[ 5  9 17]
0.7223537275031262
[21  3 14]
0.7223537275031262
[11  9 19]
0.7223537275031262
[19 10  7]
0.7223537275031262
[ 4 21 13]
0.7223537275031262
[ 0 16  5]
0.7223537275031262
[21 12  4]
0.7223537275031262
[ 1 10  9]
0.7223537275031262
[23 17 21]
0.7223537275031262
[ 0  4 10]
0.7223537275031262
[ 9 14 16]
0.7223537275031262
[17 25  9]
0.7223537275031262
[15 27 26]
0.7223537275031262
[22  1  6]
0.7223537275031262
[20 26  7]
0.7223537275031262
[ 3 10  1]
0.7223537275031262
[20 15  7]
0.7223537275031262
[ 9 13  2]
0.7223537275031262
[17 26 25]
0.7223537275031262
[15 28  1]
0.7223537275031262
[11  4  6]
0.7223537275031262
[27  7 21]
0.7223537275031262
[18  7 26]
0.7223537275031262
[26  4 16]
0.7223537275031262
[28 13 21]
0.7223537275031262
Generation 06 | Best MCC = 0.733 | Mean MCC = 0.716
[10 13  8]
0.7223537275031262
[23  2 22]
0.7223537275031262
[28 14 10]
0.7223537275031262
[19  1 25]
0.7223537275031262
[24  6  8]
0.7223537275031262
[25 12 16]
0.7223537275031262
[12 18 28]
0.7223537275031262
[ 9 11  5]
0.7332564281316
[25  4 17]
0.7223537275031262
[20  3 27]
0.7223537275031262
[11  9  8]
0.7332564281316
[9 4 1]
0.7223537275031262
[ 8 28  5]
0.7223537275031262
[26 19 28]
0.7223537275031262
[26  3  1]
0.7223537275031262
[19 29  0]
0.7223537275031262
[ 5 13 20]
0.7223537275031262
[ 2 13 19]
0.7223537275031262
[25  6  0]
0.7223537275031262
[ 1 18 21]
0.7223537275031262
[11 13 27]
0.7332564281316
[ 7 21  2]
0.7223537275031262
[ 5 16 26]
0.7223537275031262
[15 14 24]
0.7223537275031262
[ 3  5 16]
0.7223537275031262
[ 5 14 27]
0.7223537275031262
[ 0 21 17]
0.7223537275031262
[25 28 22]
0.7223537275031262
[ 7 19  0]
0.7223537275031262
[24 13 23]
0.7223537275031262
Generation 07 | Best MCC = 0.733 | Mean MCC = 0.724
[10 16  7]
0.7223537275031262
[ 5  0 26]
0.7332564281316
[29 11 25]
0.7332564281316
[24 28  2]
0.7223537275031262
[ 0 29 17]
0.7332564281316
[15  1 14]
0.7223537275031262
[11  8 21]
0.7332564281316
[ 9 12 24]
0.7223537275031262
[23 28  3]
0.7223537275031262
[ 8  6 28]
0.7332564281316
[17 19 28]
0.7223537275031262
[ 2 19 17]
0.7223537275031262
[ 8 14 10]
0.7332564281316
[ 3 24  4]
0.7223537275031262
[14  7 13]
0.7223537275031262
[ 0 21  8]
0.7332564281316
[10 12  6]
0.7223537275031262
[25 21 16]
0.7332564281316
[26 14 15]
0.7223537275031262
[ 3 21  4]
0.7332564281316
[10 18 16]
0.7223537275031262
[22 21  6]
0.7332564281316
[19 26 24]
0.7223537275031262
[ 3 21 16]
0.7332564281316
[ 4 28 20]
0.7223537275031262
[ 5 10  6]
0.7223537275031262
[ 6 18 29]
0.7223537275031262
[23  3  1]
0.7223537275031262
[26 29 23]
0.7223537275031262
[ 1 27 18]
0.7223537275031262
Generation 08 | Best MCC = 0.733 | Mean MCC = 0.726
[26 18  9]
0.7332564281316
[28 27  5]
0.7223537275031262
[ 4  2 29]
0.7332564281316
[12 20 17]
0.7332564281316
[11 15 14]
0.7223537275031262
[11 16 24]
0.7332564281316
[14  7  2]
0.7332564281316
[ 9 17  8]
0.7223537275031262
[21  4 14]
0.7223537275031262
[29 23 13]
0.7332564281316
[26 17 11]
0.7223537275031262
[23 19 15]
0.7223537275031262
[18  1 26]
0.7332564281316
[23  4 16]
0.7332564281316
[ 1 22 14]
0.7332564281316
[14 12  0]
0.7332564281316
[ 6 28  8]
0.7223537275031262
[25 18 10]
0.7332564281316
[21 20 19]
0.7332564281316
[16  4  5]
0.7332564281316
[29 13 12]
0.7332564281316
[28 21  1]
0.7223537275031262
[0 8 1]
0.7332564281316
[12 22 26]
0.7332564281316
[ 0 21 23]
0.7332564281316
[21 11 13]
0.7332564281316
[29  3 23]
0.7332564281316
[25 20  5]
0.7332564281316
[ 5 21  2]
0.7332564281316
[28 16 11]
0.7332564281316
Generation 09 | Best MCC = 0.733 | Mean MCC = 0.730
[21  4 16]
0.7332564281316
[ 4 25  3]
0.7332564281316
[ 0  8 18]
0.7332564281316
[13  8 24]
0.7332564281316
[ 2 29 22]
0.7332564281316
[29  9  8]
0.7332564281316
[ 6 12 25]
0.7332564281316
[4 1 3]
0.7332564281316
[ 1 28 24]
0.7332564281316
[13 15 26]
0.7332564281316
[11 18 27]
0.7332564281316
[29 16 18]
0.7332564281316
[13 27 16]
0.7332564281316
[ 9  8 25]
0.7332564281316
[ 2 14 25]
0.7332564281316
[19 20  1]
0.7332564281316
[27  9 17]
0.7332564281316
[ 5 12  7]
0.7332564281316
[13 26 12]
0.7332564281316
[16 15  8]
0.7332564281316
[25 27  1]
0.7332564281316
[11 13 19]
0.7332564281316
[13 25 20]
0.7332564281316
[ 9 20 14]
0.7332564281316
[15  9 10]
0.7332564281316
[ 1 25 20]
0.7332564281316
[13 28  9]
0.7332564281316
[12  3 17]
0.7332564281316
[12 15 23]
0.7332564281316
[24 14  5]
0.7332564281316
Generation 10 | Best MCC = 0.733 | Mean MCC = 0.733
[ 1  5 17]
0.7332564281316
[27 25 13]
0.7332564281316
[19  9 28]
0.7332564281316
[ 2 21 27]
0.7332564281316
[11 16  9]
0.7332564281316
[24 25  3]
0.7332564281316
[29 15 14]
0.7332564281316
[17  4 13]
0.7332564281316
[14  9 18]
0.7332564281316
[28 22 13]
0.7332564281316
[ 6 15  7]
0.7332564281316
[29 11 19]
0.7332564281316
[13 27  0]
0.7332564281316
[29  7 22]
0.7332564281316
[21 11 10]
0.7332564281316
[ 7 20  2]
0.7332564281316
[16 25  3]
0.7332564281316
[ 4 28  1]
0.7332564281316
[19 15 18]
0.7332564281316
[12  6  9]
0.7332564281316
[10 29  5]
0.7332564281316
[24  7 26]
0.7332564281316
[26 13 28]
0.7332564281316
[15 25  6]
0.7332564281316
[ 4 16 13]
0.7332564281316
[12 22 21]
0.7332564281316
[ 5  1 15]
0.7332564281316
[15  8 25]
0.7332564281316
[ 0 13 12]
0.7332564281316
[23 10 27]
0.7332564281316
Generation 11 | Best MCC = 0.733 | Mean MCC = 0.733
[ 0 22 17]
0.7332564281316
[1 0 7]
0.7332564281316
[24 10  8]
0.7332564281316
[12 10 13]
0.7332564281316
[14  9 18]
0.7332564281316
[0 7 2]
0.7332564281316
[20 12 24]
0.7332564281316
[21 24 25]
0.7332564281316
[27 28 21]
0.7332564281316
[14 26  4]
0.7332564281316
[ 9 13 29]
0.7332564281316
[ 9 18  7]
0.7332564281316
[25  2 27]
0.7332564281316
[ 7  1 11]
0.7332564281316
[24 11 18]
0.7332564281316
[22  9 28]
0.7332564281316
[ 1 11 16]
0.7332564281316
[29 14 26]
0.7332564281316
[23 29  5]
0.7332564281316
[8 9 0]
0.7332564281316
[21 11 17]
0.7332564281316
[ 6 13 25]
0.7332564281316
[ 7  0 22]
0.7332564281316
[13 25  4]
0.7332564281316
[18  8 22]
0.7332564281316
[25 23  0]
0.7332564281316
[15 18 23]
0.7332564281316
[ 7 25 20]
0.7332564281316
[ 9 18 21]
0.7332564281316
[28  1 23]
0.7332564281316
Generation 12 | Best MCC = 0.733 | Mean MCC = 0.733